### ISSUE TITLE
Dev47MC账号管理的打开问题= =

### ISSUE THREAD

**Issue by NotKiller233** [Corona-Studio/LXIT#13]
点击ID无法打开MC账号的管理界面
![LX](https://user-images.githubusercontent.com/64841155/123207329-cdcd7b00-d4ef-11eb-93e2-68801cd644d1.gif)
老版本的Lx是可以打开的

**Comment by NotKiller233** [comment]
操作平台:Windows 10 专业工作站版 Insider Perview(Build 21390)

**Comment by laolarou726** [comment]
已解决

**Comment by NotKiller233** [comment]
www
