### ISSUE TITLE
Dev48图片背景的删除BUG

### ISSUE THREAD

**Issue by NotKiller233** [Corona-Studio/LXIT#14]
删除仅有的一张图片后仍会在列表重显示
![lx](https://user-images.githubusercontent.com/64841155/123541285-52c9c600-d776-11eb-88fe-c736c69ee192.gif)
重启Lx后列表会清空，重新添加图片无法立即使用
![图片](https://user-images.githubusercontent.com/64841155/123541328-8573be80-d776-11eb-91f5-f0fe29aaed95.png)
再次重启
![图片](https://user-images.githubusercontent.com/64841155/123541351-a9cf9b00-d776-11eb-9b4e-aa265d22a3e0.png)

**Comment by laolarou726** [comment]
已修复
