### ISSUE TITLE
让StringEmptyFallBackValueConverter支持全球化

### ISSUE THREAD

**Issue by CodingEric** [Corona-Studio/LXIT#2]
当前的SEFBVC不支持主程序的i18n功能，为了实现文本统一，建议进行更改。
提供一个思路：converter先把parameter从i18n文本库里匹配，若匹配不到再直接返回parameter。

**Comment by laolarou726** [comment]
这个问题不需要修正，直接给 command parameter 传 dynamic resource 就行了
