### ISSUE TITLE
Too many prompt messages appear during the registration process 

### ISSUE THREAD

**Issue by BiDuang** [Corona-Studio/LXIT#24]
The textbox in registration process will display too many notice when password don't meet the requirements. 

![图片](https://github.com/Corona-Studio/LXIT/assets/40264028/ae6a841c-cabc-456e-b8c9-223032b43fe4)

**Comment by laolarou726** [comment]
Fixed:
<img width="542" alt="image" src="https://github.com/Corona-Studio/LXIT/assets/25716486/083a4314-3c98-4f74-8b2b-4d7940a65ec1">
